import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { sendPasswordReset } from '../api/firebaseRest';
import { useAuth } from '../context/AuthContext';

export function Login(){ const { login, loading }=useAuth(); const nav=useNavigate(); const location=useLocation(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('');
 return <AuthShell title="Welcome back" subtitle="Sign in to continue your ElectroWave journey"><form onSubmit={async e=>{e.preventDefault();setError('');try{await login(email,password);nav(location.state?.from||'/')}catch(err){setError(err.message)}}}><Field label="Email" type="email" value={email} setValue={setEmail}/><Field label="Password" type="password" value={password} setValue={setPassword}/>{error&&<div className="error-box">{error}</div>}<button className="primary-btn full" disabled={loading}>{loading?'Signing in…':'Sign in'}</button></form><p className="auth-link"><Link to="/forgot-password">Forgot password?</Link></p><p className="auth-bottom">New here? <Link to="/signup">Create an account</Link></p></AuthShell> }

export function Signup(){ const { register, loading }=useAuth(); const nav=useNavigate(); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); return <AuthShell title="Create your account" subtitle="Save addresses, track orders and build your tech cart"><form onSubmit={async e=>{e.preventDefault();setError('');try{await register(name,email,password);nav('/')}catch(err){setError(err.message)}}}><Field label="Name" value={name} setValue={setName}/><Field label="Email" type="email" value={email} setValue={setEmail}/><Field label="Password" type="password" value={password} setValue={setPassword}/>{error&&<div className="error-box">{error}</div>}<button className="primary-btn full" disabled={loading}>{loading?'Creating…':'Create account'}</button></form><p className="auth-bottom">Already have an account? <Link to="/login">Sign in</Link></p></AuthShell> }

export function ForgotPassword(){ const [email,setEmail]=useState(''); const [status,setStatus]=useState(''); const [error,setError]=useState(''); return <AuthShell title="Reset your password" subtitle="We’ll send a reset link to your email"><form onSubmit={async e=>{e.preventDefault();setError('');try{await sendPasswordReset(email);setStatus('Reset email sent. Check your inbox.')}catch(err){setError(err.message)}}}><Field label="Email" type="email" value={email} setValue={setEmail}/>{status&&<div className="success-box">{status}</div>}{error&&<div className="error-box">{error}</div>}<button className="primary-btn full">Send reset link</button></form><p className="auth-bottom"><Link to="/login">← Back to sign in</Link></p></AuthShell> }

function Field({label,type='text',value,setValue}){return <label className="field"><span>{label}</span><input required type={type} value={value} onChange={e=>setValue(e.target.value)} /></label>}
function AuthShell({title,subtitle,children}){return <main className="auth-page"><div className="auth-card"><div className="auth-logo"><span className="brand-mark">⚡</span> ElectroWave</div><h1>{title}</h1><p>{subtitle}</p>{children}</div></main>}
