import { Link, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { dbGet, dbPatch, dbPost, firebaseConfigured } from '../api/firebaseRest';
import { useCart } from '../context/CartContext';
import { useAuth } from '../context/AuthContext';

export function Cart(){ const {items,subtotal,increase,decrease,remove}=useCart(); if(!items.length)return <main className="section-shell empty-state cart-empty"><div>🛒</div><h1>Your cart is waiting</h1><p>Add a few tech essentials and come back here.</p><Link to="/products" className="primary-btn">Start shopping</Link></main>; return <main className="section-shell cart-page"><div className="section-head"><div><p className="eyebrow">YOUR BAG</p><h1>Shopping cart</h1></div></div><div className="cart-grid"><div className="cart-items">{items.map(i=><div className="cart-row" key={i.id}><img src={i.image} alt=""/><div className="cart-main"><div className="muted small">{i.brand} · {i.category}</div><Link to={`/products/${i.id}`}><h3>{i.name}</h3></Link><div className="cart-controls"><div className="stepper"><button onClick={()=>decrease(i.id)}>−</button><b>{i.quantity}</b><button onClick={()=>increase(i.id)}>+</button></div><button className="remove-btn" onClick={()=>remove(i.id)}>Remove</button></div></div><strong>₹{(i.price*i.quantity).toLocaleString('en-IN')}</strong></div>)}</div><Summary subtotal={subtotal}/></div></main> }

export function Checkout(){ const {items,subtotal,clear}=useCart(); const {user,auth}=useAuth(); const nav=useNavigate(); const [form,setForm]=useState({name:user?.name||'',phone:user?.phone||'',house:'',area:'',city:'Noida',pincode:''}); const [error,setError]=useState(''); const [placing,setPlacing]=useState(false); const total=subtotal>0?subtotal+49:0; if(!items.length)return <main className="section-shell empty-state"><h2>No items to checkout</h2><Link to="/products" className="primary-btn">Shop now</Link></main>;
 const update=e=>setForm({...form,[e.target.name]:e.target.value}); const place=async e=>{e.preventDefault();setError('');setPlacing(true); const order={userId:user?.uid||'demo-user',items:items.map(({id,name,price,quantity,image})=>({productId:id,name,price,quantity,image})),subtotal,deliveryFee:49,totalAmount:total,address:form,paymentMethod:'COD',status:'processing',createdAt:new Date().toISOString()}; try{ if(!firebaseConfigured()) { const local=JSON.parse(localStorage.getItem('electrowave_orders')||'[]'); localStorage.setItem('electrowave_orders',JSON.stringify([{...order,id:`DEMO-${Date.now()}`},...local])); } else {await dbPost('orders',order,auth.idToken);} clear();nav('/orders',{state:{placed:true}});}catch(err){setError(err.message)}finally{setPlacing(false)}};
 return <main className="section-shell checkout-page"><Link to="/cart" className="back-link">← Back to cart</Link><div className="checkout-grid"><form className="checkout-form" onSubmit={place}><p className="eyebrow">DELIVERY</p><h1>Where should we send it?</h1><div className="form-grid"><Input label="Full name" name="name" value={form.name} onChange={update}/><Input label="Phone" name="phone" value={form.phone} onChange={update}/><Input label="House / flat" name="house" value={form.house} onChange={update}/><Input label="Area / street" name="area" value={form.area} onChange={update}/><Input label="City" name="city" value={form.city} onChange={update}/><Input label="Pincode" name="pincode" value={form.pincode} onChange={update}/></div><div className="payment-box"><h3>Payment method</h3><label className="payment-option"><input type="radio" checked readOnly/><span><b>Cash on Delivery</b><small>Pay when your order arrives.</small></span><b>COD</b></label></div>{error&&<div className="error-box">{error}</div>}<button disabled={placing} className="primary-btn full">{placing?'Placing order…':'Place COD order'}</button></form><Summary subtotal={subtotal} checkout /></div></main> }

function Input({label,name,value,onChange}){return <label className="field"><span>{label}</span><input required name={name} value={value} onChange={onChange}/></label>}
function Summary({subtotal,checkout=false}){const total=subtotal+49;return <aside className="summary-card"><h3>Order summary</h3><div><span>Subtotal</span><b>₹{subtotal.toLocaleString('en-IN')}</b></div><div><span>Delivery</span><b>₹49</b></div><div className="summary-total"><span>Total</span><b>₹{total.toLocaleString('en-IN')}</b></div>{!checkout&&<Link to="/checkout" className="primary-btn full">Proceed to checkout</Link>}</aside>}

export function Orders(){ const {auth,user}=useAuth(); const [orders,setOrders]=useState(()=>JSON.parse(localStorage.getItem('electrowave_orders')||'[]').filter(o=>!user||o.userId===user.uid||o.userId==='demo-user')); const [loading,setLoading]=useState(firebaseConfigured()); useState(()=>{ if(firebaseConfigured()&&auth?.idToken){dbGet('orders',auth.idToken).then(data=>{const list=Object.entries(data||{}).map(([id,o])=>({id,...o})).filter(o=>o.userId===auth.uid).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));setOrders(list);}).catch(()=>{}).finally(()=>setLoading(false)); } }); return <main className="section-shell orders-page"><p className="eyebrow">ORDER HISTORY</p><h1>Your orders</h1>{loading?<p className="muted">Loading orders…</p>:!orders.length?<div className="empty-state"><div>📦</div><h2>No orders yet</h2><p>Your first order will appear here.</p><Link to="/products" className="primary-btn">Explore products</Link></div>:<div className="orders-list">{orders.map(o=><article className="order-card" key={o.id}><div className="order-head"><div><b>Order #{String(o.id).slice(-8).toUpperCase()}</b><span>{new Date(o.createdAt).toLocaleString()}</span></div><span className={`status ${o.status}`}>{o.status}</span></div><div className="order-products">{o.items.map(i=><div key={i.productId}><img src={i.image} alt=""/><span>{i.name} × {i.quantity}</span><b>₹{(i.price*i.quantity).toLocaleString('en-IN')}</b></div>)}</div><div className="order-foot"><span>Payment: {o.paymentMethod}</span><b>Total ₹{o.totalAmount.toLocaleString('en-IN')}</b></div><div className="trackline"><span className={['processing','shipped','delivered'].includes(o.status)?'done':''}>● Placed</span><i></i><span className={['shipped','delivered'].includes(o.status)?'done':''}>● Shipped</span><i></i><span className={o.status==='delivered'?'done':''}>● Delivered</span></div></article>)}</div>}</main> }

export function Profile(){ const {user,updateProfile}=useAuth(); const [name,setName]=useState(user?.name||''); const [phone,setPhone]=useState(user?.phone||''); const [addresses,setAddresses]=useState(user?.addresses||[]); const [saved,setSaved]=useState(''); const [address,setAddress]=useState({label:'Home',house:'',area:'',city:'Noida',pincode:''}); const save=async()=>{await updateProfile({name,phone,addresses});setSaved('Profile updated');setTimeout(()=>setSaved(''),2000)}; const addAddress=()=>{if(!address.house||!address.pincode)return; const next=[...addresses,{...address,id:Date.now()}];setAddresses(next);setAddress({label:'Home',house:'',area:'',city:'Noida',pincode:''});}; const remove=a=>setAddresses(addresses.filter(x=>x.id!==a.id)); return <main className="section-shell profile-page"><p className="eyebrow">YOUR ACCOUNT</p><h1>Profile</h1><div className="profile-grid"><section className="panel"><h3>Personal information</h3><label className="field"><span>Name</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Email</span><input value={user?.email||''} disabled/></label><label className="field"><span>Phone</span><input value={phone} onChange={e=>setPhone(e.target.value)}/></label><button className="primary-btn" onClick={save}>Save changes</button>{saved&&<div className="success-box">{saved}</div>}</section><section className="panel"><h3>Saved addresses</h3>{addresses.map(a=><div className="address-card" key={a.id}><div><b>{a.label}</b><p>{a.house}, {a.area}, {a.city} — {a.pincode}</p></div><button className="remove-btn" onClick={()=>remove(a)}>Remove</button></div>)}<div className="address-form"><h4>Add another address</h4><div className="form-grid"><Input label="Label" name="label" value={address.label} onChange={e=>setAddress({...address,label:e.target.value})}/><Input label="House / flat" name="house" value={address.house} onChange={e=>setAddress({...address,house:e.target.value})}/><Input label="Area" name="area" value={address.area} onChange={e=>setAddress({...address,area:e.target.value})}/><Input label="City" name="city" value={address.city} onChange={e=>setAddress({...address,city:e.target.value})}/><Input label="Pincode" name="pincode" value={address.pincode} onChange={e=>setAddress({...address,pincode:e.target.value})}/></div><button className="secondary-btn" onClick={addAddress}>+ Save address</button></div></section></div></main> }
