export const categories = [
  { id: 'audio', name: 'Audio', emoji: '🎧', accent: 'Violet' },
  { id: 'mobile', name: 'Mobiles', emoji: '📱', accent: 'Blue' },
  { id: 'wearables', name: 'Wearables', emoji: '⌚', accent: 'Mint' },
  { id: 'computing', name: 'Computing', emoji: '💻', accent: 'Orange' },
  { id: 'gaming', name: 'Gaming', emoji: '🎮', accent: 'Pink' },
  { id: 'power', name: 'Power & Cables', emoji: '🔋', accent: 'Yellow' },
  { id: 'smart-home', name: 'Smart Home', emoji: '🏠', accent: 'Cyan' },
  { id: 'cameras', name: 'Cameras', emoji: '📷', accent: 'Red' }
];

export const products = [
  { id:'p1', name:'PulsePods Air Pro', brand:'Pulse', categoryId:'audio', category:'Audio', price:2499, oldPrice:3499, rating:4.7, reviews:312, badge:'BESTSELLER', image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=800&q=85', description:'Adaptive ANC earbuds with low-latency mode, wireless charging and a compact case.', specs:['Active Noise Cancellation','42h total battery','Bluetooth 5.4','IPX5'] },
  { id:'p2', name:'NovaSound Studio 45', brand:'NovaSound', categoryId:'audio', category:'Audio', price:5499, oldPrice:6999, rating:4.8, reviews:184, badge:'DEAL', image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=85', description:'Over-ear wireless headphones tuned for deep bass and long study sessions.', specs:['40h battery','Hybrid ANC','Multipoint','USB-C fast charge'] },
  { id:'p3', name:'OrbitWatch X2', brand:'Orbit', categoryId:'wearables', category:'Wearables', price:3299, oldPrice:4999, rating:4.5, reviews:228, badge:'TRENDING', image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=85', description:'AMOLED smart watch with wellness tracking, calling and a lightweight metal frame.', specs:['1.78" AMOLED','Bluetooth calling','100+ sports modes','7-day battery'] },
  { id:'p4', name:'AeroBook 14', brand:'Aero', categoryId:'computing', category:'Computing', price:58999, oldPrice:64999, rating:4.6, reviews:97, badge:'NEW', image:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=85', description:'Slim performance laptop with a crisp display and all-day productivity battery.', specs:['14" 2.8K display','16GB RAM','512GB SSD','Backlit keyboard'] },
  { id:'p5', name:'VisionDock 27', brand:'Vision', categoryId:'computing', category:'Computing', price:13999, oldPrice:16999, rating:4.4, reviews:141, badge:'DEAL', image:'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=85', description:'27-inch borderless monitor designed for creators, coding and gaming.', specs:['27" QHD','100Hz refresh','HDR-ready','USB-C input'] },
  { id:'p6', name:'HyperKey 75', brand:'Hyper', categoryId:'gaming', category:'Gaming', price:4799, oldPrice:5999, rating:4.7, reviews:168, badge:'HOT', image:'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=85', description:'Compact mechanical keyboard with tactile switches and customizable lighting.', specs:['75% layout','Hot-swappable','2.4G + Bluetooth','RGB lighting'] },
  { id:'p7', name:'GameCore X Controller', brand:'GameCore', categoryId:'gaming', category:'Gaming', price:2699, oldPrice:3499, rating:4.5, reviews:203, badge:'VALUE', image:'https://images.unsplash.com/photo-1605901309584-818e25960a8f?auto=format&fit=crop&w=800&q=85', description:'Ergonomic wireless controller with precision sticks and dual rumble motors.', specs:['Wireless + wired','Hall-effect sticks','20h battery','Dual vibration'] },
  { id:'p8', name:'ChargeFlex GaN 65W', brand:'ChargeFlex', categoryId:'power', category:'Power & Cables', price:1799, oldPrice:2499, rating:4.8, reviews:415, badge:'BEST VALUE', image:'https://images.unsplash.com/photo-1591290619762-0c4d4e9b3e13?auto=format&fit=crop&w=800&q=85', description:'Pocket-friendly GaN charger with three fast charging ports.', specs:['65W output','2x USB-C + USB-A','PD 3.0','Universal input'] },
  { id:'p9', name:'VoltBank 20K', brand:'Volt', categoryId:'power', category:'Power & Cables', price:2199, oldPrice:2999, rating:4.6, reviews:376, badge:'POPULAR', image:'https://images.unsplash.com/photo-1609592424254-bb3b1e12a0c2?auto=format&fit=crop&w=800&q=85', description:'High-capacity power bank with dual device charging and LED battery display.', specs:['20,000mAh','22.5W fast charge','Dual USB-C','Digital display'] },
  { id:'p10', name:'NestCam Mini 2K', brand:'Nestify', categoryId:'smart-home', category:'Smart Home', price:2999, oldPrice:3999, rating:4.4, reviews:121, badge:'NEW', image:'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?auto=format&fit=crop&w=800&q=85', description:'Compact indoor security camera with smart alerts and two-way audio.', specs:['2K video','Night vision','Motion alerts','Two-way audio'] },
  { id:'p11', name:'SnapCam 4K Pocket', brand:'Snap', categoryId:'cameras', category:'Cameras', price:12999, oldPrice:14999, rating:4.3, reviews:88, badge:'CREATOR PICK', image:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=85', description:'Pocket camera for everyday vlogs with stabilized 4K video.', specs:['4K 30fps','3-axis stabilization','Wi-Fi transfer','Flip screen'] },
  { id:'p12', name:'PixelOne 5G', brand:'PixelOne', categoryId:'mobile', category:'Mobiles', price:23999, oldPrice:26999, rating:4.6, reviews:256, badge:'JUST IN', image:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=85', description:'Slim 5G phone with a bright OLED display and a clean everyday camera setup.', specs:['120Hz OLED','8GB RAM','128GB storage','5000mAh battery'] }
];
