export const categories = [
  { id: 'headphones', name: 'Headphones', emoji: '🎧', accent: 'Violet' },
  { id: 'wireless-earbuds', name: 'Wireless Earbuds', emoji: '🎶', accent: 'Blue' },
  { id: 'speakers', name: 'Speakers', emoji: '🔊', accent: 'Mint' },
  { id: 'charger-cable', name: 'Charger & Cable', emoji: '🔌', accent: 'Orange' },
  { id: 'gaming-series', name: 'Gaming Series', emoji: '🎮', accent: 'Pink' },
  { id: 'smart-watches', name: 'Smart Watches', emoji: '⌚', accent: 'Yellow' },
  { id: 'mobile', name: 'Mobile', emoji: '📱', accent: 'Cyan' },
  { id: 'laptop', name: 'Laptop', emoji: '💻', accent: 'Red' }
];

export const products = [
  { id:'p1', name:'AeroBeat Pro ANC', brand:'Noviq', categoryId:'headphones', category:'Headphones', price:5499, oldPrice:6999, rating:4.8, reviews:384, badge:'BESTSELLER', image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1000&q=88', description:'Premium over-ear headphones with adaptive noise cancellation, deep bass and an all-day comfort fit.', specs:['Adaptive ANC','45h battery','Bluetooth 5.4','USB-C fast charge'] },
  { id:'p2', name:'SonicLoop 700', brand:'Noviq', categoryId:'headphones', category:'Headphones', price:3299, oldPrice:4499, rating:4.6, reviews:221, badge:'DEAL', image:'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1000&q=88', description:'Lightweight wireless headphones tuned for everyday music, calls and travel.', specs:['40h battery','Dual-mic calls','Low-latency mode','Foldable design'] },
  { id:'p3', name:'PulsePods Air X', brand:'Noviq', categoryId:'wireless-earbuds', category:'Wireless Earbuds', price:2499, oldPrice:3499, rating:4.7, reviews:512, badge:'HOT', image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=1000&q=88', description:'Compact ANC earbuds with punchy sound, wireless charging and a pocket-friendly case.', specs:['Active Noise Cancellation','36h total battery','Bluetooth 5.4','IPX5'] },
  { id:'p4', name:'AirDots Max Lite', brand:'Noviq', categoryId:'wireless-earbuds', category:'Wireless Earbuds', price:1899, oldPrice:2499, rating:4.5, reviews:311, badge:'POPULAR', image:'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=1000&q=88', description:'Clear-call true wireless earbuds designed for work, workouts and commute.', specs:['30h total battery','ENC calls','Touch controls','IPX4'] },
  { id:'p5', name:'BassBox Mini 20W', brand:'Noviq', categoryId:'speakers', category:'Speakers', price:2699, oldPrice:3499, rating:4.6, reviews:276, badge:'TRENDING', image:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1000&q=88', description:'Portable Bluetooth speaker with room-filling bass and a rugged carry-friendly body.', specs:['20W output','14h playtime','Bluetooth 5.3','IP67'] },
  { id:'p6', name:'SoundDock Glow', brand:'Noviq', categoryId:'speakers', category:'Speakers', price:3999, oldPrice:4999, rating:4.7, reviews:149, badge:'NEW', image:'https://images.unsplash.com/photo-1589003077984-894e133dabab?auto=format&fit=crop&w=1000&q=88', description:'Desktop wireless speaker with punchy stereo sound and a soft ambient light ring.', specs:['30W stereo','18h battery','Party mode','USB-C'] },
  { id:'p7', name:'ChargeHub GaN 65W', brand:'Noviq', categoryId:'charger-cable', category:'Charger & Cable', price:1799, oldPrice:2499, rating:4.8, reviews:648, badge:'BEST VALUE', image:'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1000&q=88', description:'Compact multi-port GaN charger for phones, tablets and laptops with fast USB-C PD.', specs:['65W PD output','2x USB-C + USB-A','GaN cooling','Universal input'] },
  { id:'p8', name:'FlexCharge Braided Cable', brand:'Noviq', categoryId:'charger-cable', category:'Charger & Cable', price:699, oldPrice:999, rating:4.7, reviews:732, badge:'VALUE', image:'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=1000&q=88', description:'Durable braided fast-charge cable built for everyday charging and sync.', specs:['100W support','1.5m length','Braided nylon','Data + charge'] },
  { id:'p9', name:'BassLink Wired Earphones', brand:'Noviq', categoryId:'charger-cable', category:'Charger & Cable', price:599, oldPrice:799, rating:4.4, reviews:419, badge:'EVERYDAY', image:'https://images.unsplash.com/photo-1588449668365-d15e397f6787?auto=format&fit=crop&w=1000&q=88', description:'Reliable wired earphones with balanced audio and an in-line microphone.', specs:['3.5mm jack','In-line mic','Tangle-resistant cable','Deep bass'] },
  { id:'p10', name:'NeckBeat N1', brand:'Noviq', categoryId:'charger-cable', category:'Charger & Cable', price:1299, oldPrice:1799, rating:4.5, reviews:286, badge:'POPULAR', image:'https://images.unsplash.com/photo-1598331668826-20cecc596b0c?auto=format&fit=crop&w=1000&q=88', description:'Flexible Bluetooth neckband for calls, music and long commutes.', specs:['30h battery','Magnetic buds','ENC calls','Fast charge'] },
  { id:'p11', name:'GameForge H7', brand:'Noviq', categoryId:'gaming-series', category:'Gaming Series', price:3299, oldPrice:4499, rating:4.8, reviews:205, badge:'GAMER PICK', image:'https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=1000&q=88', description:'Low-latency gaming headset with positional audio, a flexible mic and lightweight fit.', specs:['7.1 virtual surround','Low latency','Detachable mic','RGB accents'] },
  { id:'p12', name:'GameForge H9 Wireless', brand:'Noviq', categoryId:'gaming-series', category:'Gaming Series', price:4499, oldPrice:5999, rating:4.7, reviews:174, badge:'NEW', image:'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1000&q=88', description:'Wireless gaming headphones built for immersive sessions with rich bass and clear chat.', specs:['2.4GHz wireless','30h battery','Flip mic','USB-C'] },
  { id:'p13', name:'Orbit Watch S2', brand:'Noviq', categoryId:'smart-watches', category:'Smart Watches', price:3499, oldPrice:4999, rating:4.6, reviews:392, badge:'TRENDING', image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=88', description:'AMOLED smartwatch with calling, fitness tracking and a clean metal-inspired frame.', specs:['1.78-inch AMOLED','Bluetooth calling','100+ sports modes','7-day battery'] },
  { id:'p14', name:'Pulse M5 5G', brand:'Noviq', categoryId:'mobile', category:'Mobile', price:23999, oldPrice:26999, rating:4.5, reviews:167, badge:'JUST IN', image:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1000&q=88', description:'Slim 5G smartphone with a vivid display, capable cameras and all-day battery life.', specs:['120Hz OLED','8GB RAM','128GB storage','5000mAh battery'] },
  { id:'p15', name:'NoviqBook Air 14', brand:'Noviq', categoryId:'laptop', category:'Laptop', price:58999, oldPrice:64999, rating:4.7, reviews:98, badge:'CREATOR PICK', image:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1000&q=88', description:'Slim performance laptop built for coding, creative work and everyday productivity.', specs:['14-inch 2.8K display','16GB RAM','512GB SSD','Backlit keyboard'] },
  { id:'p16', name:'NoviqBook Pro 16', brand:'Noviq', categoryId:'laptop', category:'Laptop', price:82999, oldPrice:94999, rating:4.8, reviews:74, badge:'PREMIUM', image:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=88', description:'Large-screen performance laptop with a high-refresh display and desktop-class multitasking.', specs:['16-inch 165Hz display','16GB RAM','1TB SSD','Advanced cooling'] }
];
